/*----------------------------------------------------------
MASV:19120644
HO TEN:Lê Đức Tâm
LAB: 03
NGAY:25/04/2022
----------------------------------------------------------*/
--a)
CREATE DATABASE QLSV;
USE QLSV;
GO
--DROP TABLE SINHVIEN
--DROP TABLE LOP
--DROP TABLE NHANVIEN

/*----------------------------------------------------------
MASV:19120644
HO TEN:Lê Đức Tâm
LAB: 03
NGAY:25/04/2022
----------------------------------------------------------*/
--b)
CREATE TABLE SINHVIEN(
    MASV NVARCHAR(20) NOT NULL ,
    HOTEN NVARCHAR(20) NOT NULL ,
    NGAYSINH DATETIME,
    DIACHI NVARCHAR(200),
    MALOP VARCHAR(20),
    TENDN NVARCHAR(100) NOT NULL UNIQUE ,
    MATKHAU VARBINARY(MAX) NOT NULL
    CONSTRAINT PK_SINHVIEN PRIMARY KEY (MASV)
);

CREATE TABLE NHANVIEN(
    MANV NVARCHAR(20) NOT NULL ,
    HOTEN NVARCHAR(20) NOT NULL ,
    EMAIL NVARCHAR(20),
    LUONG VARBINARY(MAX) NOT NULL,
    TENDN NVARCHAR(100) NOT NULL UNIQUE ,
    MATKHAU VARBINARY(MAX) NOT NULL
    CONSTRAINT PK_NHANVIEN PRIMARY KEY (MANV)
);

CREATE TABLE LOP(
    MALOP VARCHAR(20) NOT NULL ,
    TENLOP NVARCHAR(100) NOT NULL ,
    MANV NVARCHAR(20) ,
    CONSTRAINT PK_LOP PRIMARY KEY (MALOP)
);



ALTER TABLE LOP ADD CONSTRAINT FK_LOP_NHANVIEN FOREIGN KEY (MANV)
REFERENCES NHANVIEN (MANV)

ALTER TABLE SINHVIEN ADD CONSTRAINT FK_SINHVIEN_LOP FOREIGN KEY (MALOP)
REFERENCES LOP (MALOP)




/*----------------------------------------------------------
MASV:19120644
HO TEN:Lê Đức Tâm
LAB: 03
NGAY:25/04/2022
----------------------------------------------------------*/
--c)
-- CAU LENH TAO STORED PROCEDURE

--i)
--THEM SINH VIEN PROCEDURE
go
CREATE OR ALTER PROCEDURE SP_INS_SINHVIEN(
    @MASV NVARCHAR(20),
    @HOTEN NVARCHAR(20),
    @NGAYSINH DATETIME,
    @DIACHI NVARCHAR(200),
    @MALOP VARCHAR(20),
    @TENDN NVARCHAR(100),
    @MATKHAU NVARCHAR(100)
) AS
BEGIN
    INSERT INTO SINHVIEN (MASV, HOTEN, NGAYSINH, DIACHI, MALOP, TENDN, MATKHAU)
    VALUES (@MASV, @HOTEN, @NGAYSINH, @DIACHI, @MALOP, @TENDN, HASHBYTES('MD5', @MATKHAU))
END;

--ii)
-- THEM NHAN VIEN PROCEDURE
GO
CREATE OR ALTER PROCEDURE SP_INS_NHANVIEN(
    @MANV NVARCHAR(20),
    @HOTEN NVARCHAR(20),
    @EMAIL NVARCHAR(20),
    @LUONG int,
    @TENDN NVARCHAR(100),
    @MATKHAU NVARCHAR(100) 
) AS Begin
    IF NOT EXISTS(
        SELECT * FROM sys.symmetric_keys
        WHERE name = 'KEY_NHANVIEN'
        )
    BEGIN
        create symmetric key KEY_NHANVIEN
        with algorithm = AES_256
        encryption by password = '19120644';
    END
    open symmetric key KEY_NHANVIEN
    decryption by password = '19120644';

    INSERT INTO NHANVIEN (MANV, HOTEN, EMAIL, LUONG, TENDN, MATKHAU)
    VALUES (@MANV, @HOTEN, @EMAIL, CAST(encryptbykey(key_guid('KEY_NHANVIEN'), cast(@LUONG as varchar)) as varbinary(max)) , @TENDN, HASHBYTES('SHA1', @MATKHAU));

    close symmetric key KEY_NHANVIEN
END;

/*----------------------------------------------------------
MASV:19120644
HO TEN:Lê Đức Tâm
LAB: 03
NGAY:25/04/2022
----------------------------------------------------------*/
--d)
-- XAC MINH TAI KHOAN SINH VIEN PROCEDURE
GO
CREATE OR ALTER PROCEDURE SP_AUTHEN_SINHVIEN(
    @TENDN NVARCHAR(100),
    @MATKHAU NVARCHAR(100)
) 
AS 
BEGIN
	select MASV, HOTEN, NGAYSINH, DIACHI, MALOP from SINHVIEN
	where TENDN = @TENDN and MATKHAU = HASHBYTES('MD5', @MATKHAU);
END;

GO
CREATE OR ALTER PROCEDURE SP_AUTHEN_NHANVIEN(
    @TENDN NVARCHAR(100),
    @MATKHAU NVARCHAR(100)
) 
AS 
BEGIN
	select *
	from NHANVIEN
	where TENDN = @TENDN
		and MATKHAU = hashbytes('SHA1', @MATKHAU)
END;
GO

--INSERT NHANVIEN
exec SP_INS_NHANVIEN
	'NV01','LE VAN A','NVA@',3000000,'NVA','123456';

exec SP_INS_NHANVIEN
	'NV02','LE VAN B','NVA@',3000000,'NVB','123456';

exec SP_INS_NHANVIEN
	'NV03','LE VAN C','NVA@',3000000,'NVC','123456';

exec SP_INS_NHANVIEN
	'NV04','LE VAN D','NVA@',3000000,'NVD','123456';


--INSERT LOP
INSERT INTO LOP (MALOP, TENLOP, MANV) VALUES ('19CTT4', N'K19 CNTT lớp 4', 'NV01');
INSERT INTO LOP (MALOP, TENLOP, MANV) VALUES ('19CNTN', N'CNTT Cử nhân tài năng','NV02');
INSERT INTO LOP (MALOP, TENLOP, MANV) VALUES ('20CTT3', N'K20 CNTT lớp 3', 'NV03');
INSERT INTO LOP (MALOP, TENLOP, MANV) VALUES ('20CSH1', N'K20 CNSH lớp 1', 'NV04');

--INSERT SINHVIEN
exec SP_INS_SINHVIEN
    '19120644',N'LÊ ĐỨC TÂM','11/02/2001',N'Bình Dương','19CTT4','19120644','123456';

EXEC SP_INS_SINHVIEN 
	'SV01', 'NGUYEN VAN A', '11/1/2001', '280 AN DUONG VUONG', '19CNTN', 'SVA', '123456'

EXEC SP_INS_SINHVIEN 
	'SV02', 'NGUYEN VAN B', '07/12/2002', '280 AN DUONG VUONG', '20CSH1', 'SVB', '123456'

EXEC SP_INS_SINHVIEN 
	'SV03', 'NGUYEN VAN C', '06/07/2001', '280 AN DUONG VUONG', '19CTT4', 'SVC', '123456'





--AUTHENTICATION
EXEC SP_AUTHEN_SINHVIEN '19120644', '123456';

EXEC SP_AUTHEN_NHANVIEN 'NVA','123456';